### ISSUE TITLE
Free LBP6000 to a good home

### ISSUE THREAD

**Issue by Eunoia** [mounaiban/captdriver#35]
I'm a big fan of your work. I managed to set up my LBP6000 printer on a Raspberry Pi, but after about two weeks, it stopped working properly. It seems like I need to print a blank page from a Windows computer (or an emulated one) to trigger printing from the Raspberry Pi again. I've decided to switch to a newer Brother printer, even though it's larger than my compact LBP6000.

I'll keep the LBP6000 until April 1st, then I plan to sell it to someone who uses Windows. If you're interested, please contact me, and I'll be happy to ship you the printer so it can be used for driver development.

**Comment by mounaiban** [comment]
Hi, thanks for your offer, but I don't have the capacity to maintain another printer (I've currently got two Canon machines: my trusty little LBP3000 and another big one). Mailing these things can be really expensive and risky.

However, I would be looking for more printers in the future, only after I figure out CAPT CMYK printing. I might start with the  [LBP6200d](https://media.canon-asia.com/shared/live/products/EN/LBP6200d.pdf), an interesting member of the CAPT device family: a personal printer with automatic two-sided printing.

Also greets to Alexey and Nicolas for getting this started, and the other contributors for making this possible.

**Comment by jekader** [comment]
@mounaiban if you decide to get a new CAPT device - feel free to ping me. I can sponsor part/all of the purchace for the sake of opensource and bringing a new life to deprecated hardware.
