### ISSUE TITLE
canon lbp7010c/7018c Universal or not lbp7600？

### ISSUE THREAD

**Issue by 929355193** [mounaiban/captdriver#36]

**Comment by mounaiban** [comment]
I'm assuming that you are asking if the 7010C series is similar to the 7600 from a software point of view; they're not...

LBP7010C & LBP7018C use the CAPT protocol, [while the LBP7600 uses LIPS LX](https://oip.manual.canon/USRMA-0217-zz-SS-jaJP/contents/05010010.html).

I'm closing this issue, as it appears to concern LIPS LX support. However, supporting the 7010C and 7018C is part of our master plan. I'll still try to answer questions about the LBP7600 as much as I can.
