### ISSUE TITLE
[Alpine Linux v3.15 aarch64] Canon CAPT LBP-810 not listed under lpinfo -v

### ISSUE THREAD

**Issue by snvmk** [mounaiban/captdriver#9]
Hello, so, i installed this captdriver, but when i run `lpinfo -v`, it doesnt show my printer (Canon LBP-810). Can this dinosaur even be supported by this?

**Comment by mounaiban** [comment]
USB printers of any brand should appear under ``lpinfo -v`` even if there is no working driver installed. Do other USB printers show up on the list when you run the command?

Captdriver currently doesn't support the LBP810 as it uses the SCoA compression codec (different from Hi-SCoA, which is already supported) and has other subtle but important differences in its status register format. Support can be implemented.

There is a work in progress by @ra1nst0rm3d in [this fork](https://github.com/ra1nst0rm3d/captdriver) to support the LBP1120, another similar printer. See also agalakhov/captdriver/issues/33 and agalakhov/captdriver/issues/20.

> Note: I have closed this issue as it is has more to do with CUPS and operating system configuration but nothing to do with  Captdriver. You can still respond to the conversation which remains searchable.

**Comment by snvmk** [comment]
Okay thanks, now i dont have this printer xD bought new MFP and gave this canon to good friend
